# Generated by Django 4.2.2 on 2023-06-26 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(help_text='Tipo de género', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del libro', max_length=32)),
                ('síntesis', models.TextField(help_text='Breve síntesis de la película', max_length=150)),
                ('url', models.URLField(blank=True)),
                ('isbn', models.CharField(help_text='ISBN de 13 caracteres', max_length=13, verbose_name='ISBN')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorespeliculas.director')),
                ('genero', models.ManyToManyField(to='directorespeliculas.genero')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para ésta película', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('O', 'On loan'), ('A', 'Available'), ('R', 'Reserved')], default='M', help_text='Disponibilidad de la película', max_length=1)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorespeliculas.pelicula')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
